### ISSUE TITLE
Deliverables for a minimum viable product

### ISSUE THREAD

**Issue by kc1212** [kc1212/virtual-grid#7]
This is a non-exhaustive list of tasks that should be completed for this project. Please keep this issue up to date when new features are implemented. 

- [x] Write and test the Bully Algorithm for leader election (@kc1212, #3)
- [x] Write and test the Ricart-Agrawala for mutex (@kc1212, #6)
- [x] Investigate running VGS on DAS4/5 (@Saminobi)
- [x] Discovery server / bootstrap server (@kc1212, #10)
- [x] Maintain index of RM clusters in GS (@Saminobi, #13)
- [x] `AddJobs` remote call on GS (@kc1212, #8)
- [x] Write client code that calls `AddJob` on both GS and RM (@kc1212, #8 #14)
- [x] Job submission and scheduling on GS (@kc1212, #14)
- [x] Job scheduling on RM (@kc1212, #14)
- [ ] Design test plan (@Saminobi)
- [x] `AddJobs` remote call on RM and send job to GS when RM is busy (@kc1212, #29)
- [x] Job re-scheduling for when RM goes offline (@kc1212, #16 #26)
- [x] Job deletion on completion (@kc1212, #16 #26)
- [x] Re-synchronisation when GS recovers from failure (@kc1212, #26)
- [ ] Logging and metric collection for load analysis
